run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gofmt
    - misspell
    - gocritic
    - gosec

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
